rules = [] 
def derive(s, nonterminal):
    if s == nonterminal: 
        return True
    for rule in rules: 
        if rule[0] == nonterminal[0]: 
            pos = 0
            match = True
            for c in rule[3:]:
                if c.isupper(): 
                    match &= derive(s[pos:], c) 
                else: 
                    match &= (s[pos] == c)
                pos += 1
            if match and pos == len(s):
                return True
    return False
n = int(input()) 
start = input().strip()
for i in range(n):
    rule = input().strip() 
    rules.append(rule)
s = input().strip() 
if derive(s, start):
    print("The string can be generated by the given CFG.")
else:
    print("The string cannot be generated by the given CFG.")
